import Head from 'next/head'
import BackgroundSnow from '../components/BackgroundSnow'
import Hero from '../components/Hero'



export default function Home() {
  return (
    <div className='relative w-full h-full flex'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <BackgroundSnow/>
      <Hero/>
    </div>
  )
}
